server:
  port: 8801

spring:
  application:
    name: cloud-stream-lc-provider
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings:
        output:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8801
    prefer-ip-address: true    #访问路径显示ip
    lease-renewal-interval-in-seconds: 1  #客户端向服务端发送心跳频率
    lease-expiration-duration-in-seconds: 2 #服务端最后一次接收到心跳后，等待时间时间上限
#      defaultZone: http://localhost:7001/eureka
