server:
  port: 9527

spring:
  application:
    name: cloud-spirng-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 开启注册中心，动态创建路由，利用服务名称访问
      routes:
#        - id: payment_get_order   # 路由名称，无固定规则，要求唯一
##          uri: http://localhost:8001/  # 匹配后提供服务的地址
#          uri: lb://cloud-provider-lc-payment
#          predicates:
#            - Path=/payment/get/**  # 断言 路径匹配的进行路由
        - id: payment_get_feignTimeout   # 路由名称，无固定规则，要求唯一
            #          uri: http://localhost:8001/  # 匹配后提供服务的地址
          uri: lb://cloud-provider-lc-payment
          predicates:
            - Path=/payment/**  # 断言 路径匹配的进行路由
#            - After=2024-03-15T11:18:52.809+08:00[Asia/Shanghai]
#            - Before=2025-05-15T11:18:52.809+08:00[Asia/Shanghai]
#            - Between=2024-03-15T11:18:52.809+08:00[Asia/Shanghai],2025-05-15T11:18:52.809+08:00[Asia/Shanghai]
#            - Cookie=username,tttttzzzzz # curl --location "http://localhost:9527/payment/get/31" \ --header "Cookie: username=tttttzzzzz"
#            - Header=X-Request-Id, \d+
          filters:
#            - RewritePath=/payment/get/(?<segment>.*), /$\{segment}
            - AddRequestHeader=X-Request-red, blue

eureka:
  instance: cloud-spirng-gateway-service
  client:
    register-with-eureka: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://localhost:7001/eureka
