server:
  port: 8001

spring:
  application:
    name: cloud-provide-hystrix-payment8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true    #访问路径显示ip
    lease-renewal-interval-in-seconds: 1  #客户端向服务端发送心跳频率
    lease-expiration-duration-in-seconds: 2 #服务端最后一次接收到心跳后，等待时间时间上限
#      defaultZone: http://localhost:7001/eureka
